name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build application
        run: npm run build
        working-directory: ./frontend

      - name: Install PM2 globally (if not installed)
        run: |
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

      - name: Restart or start Next.js app with PM2
        run: |
          cd frontend
          pm2 delete nodeapp || true
          pm2 start npm --name nodeapp -- start
          pm2 save

      - name: Debug PM2 list
        run: pm2 list
