name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build application
        working-directory: ./frontend
        run: npm run build

      - name: Install PM2 globally (if not installed)
        run: |
          if ! command -v pm2 &> /dev/null; then
            npm install -g pm2
          fi

      - name: Restart or start app with PM2 (non-blocking)
        run: |
          cd frontend
          pm2 delete nodeapp || true
          pm2 start npm --name nodeapp -- start
