name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build application
        working-directory: ./frontend
        run: npm run build

      - name: Ensure PM2 is installed globally
        run: |
          if ! command -v pm2 &> /dev/null; then
            echo "Installing PM2..."
            npm install -g pm2
          else
            echo "PM2 already installed"
          fi

      - name: Restart or start app with PM2
        working-directory: ./frontend
        run: |
          pm2 describe nodeapp > /dev/null 2>&1
          if [ $? -eq 0 ]; then
            echo "Restarting existing app"
            pm2 restart nodeapp
          else
            echo "Starting app"
            pm2 start npm --name nodeapp -- start
          fi

      - name: Save PM2 state
        run: pm2 save
