name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Node App
        run: |
          cd frontend
          npm install
          npm run build
          pm2 restart nodeapp || pm2 start npm --name nodeapp -- start
